#!/bin/sh
uci get v2fly.@general[-1] >/dev/null 2>&1 || uci add v2fly general >/dev/null 2>&1
uci commit v2fly
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@v2fly[-1]
	add ucitrack v2fly
	set ucitrack.@v2fly[-1].init=v2fly
	commit ucitrack
	delete firewall.v2fly
	set firewall.v2fly=include
	set firewall.v2fly.type=script
	set firewall.v2fly.path=/var/etc/v2fly.include
	set firewall.v2fly.reload=1
	commit firewall
EOF
exit 0
