name: Build openWRT ipk/apk package

permissions:
  contents: write

on:
  push:
    tags:
        - '0.*.*'

jobs:
  build_apk:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-apk

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git wget curl unzip rsync

    - name: Download OpenWrt Snapshot SDK
      run: |
        PAGE_CONTENT=$(curl -s https://downloads.openwrt.org/snapshots/targets/x86/64/)
        # Extract SDK filenames using regular expressions (supports .tar.zst format).
        SDK_FILENAME=$(echo "$PAGE_CONTENT" | grep -oP 'openwrt-sdk-x86-64_gcc-.*?_musl\.Linux-x86_64\.tar\.zst' | head -1)
        
        if [ -z "$SDK_FILENAME" ]; then
          echo "SDK file not found"
          exit 1
        fi
        
        # Build a complete URL
        SDK_URL="https://downloads.openwrt.org/snapshots/targets/x86/64/$SDK_FILENAME"

        echo "Find the SDK file: $SDK_FILENAME"
        sdk_name=${SDK_FILENAME%.tar.zst}
        wget -c https://downloads.openwrt.org/snapshots/targets/x86/64/${sdk_name}.tar.zst
        tar axf ${sdk_name}.tar.zst
        ln -sf ${sdk_name} openwrt_sdk

    - name: Set up OpenWrt SDK
      run: |
        cd openwrt_sdk
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref_name }}
        path: openwrt_sdk/package/luci-app-xray

    - name: Build APK package
      run: |
        cd openwrt_sdk/
        make defconfig
        make package/luci-app-xray/status/{clean,compile} V=s -j$(nproc)

    - name: Upload .apk package
      id: upload_apk
      uses: actions/upload-artifact@v4
      with:
        name: luci-app-xray-apk
        path: openwrt_sdk/bin/packages/x86_64/base/luci-app-xray*.apk

  build_ipk:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-ipk

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git wget curl unzip rsync

    - name: Download OpenWrt release SDK
      run: |
        # Find SDK Name #
        PAGE_CONTENT=$(curl -s https://downloads.openwrt.org/releases/24.10.1/targets/x86/64/)
        SDK_FILENAME=$(echo "$PAGE_CONTENT" | grep -oP 'openwrt-sdk-24\.10\.1-x86-64_gcc-.*?_musl\.Linux-x86_64\.tar\.zst' | head -1)
        if [ -z "$SDK_FILENAME" ]; then
          echo "SDK file not foun"
          exit 1
        fi
        # Build Full URL
        sdk_name=${SDK_FILENAME%.tar.zst}
        wget -c https://downloads.openwrt.org/releases/24.10.1/targets/x86/64/${sdk_name}.tar.zst
        tar axf $sdk_name.tar.zst
        ln -sf $sdk_name openwrt_sdk

    - name: Set up OpenWrt SDK
      run: |
        cd openwrt_sdk
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref_name }}
        path: openwrt_sdk/package/luci-app-xray
    
    - name: Generate ChangeLog by conventional-changelog
      run: |
        npm install -g conventional-changelog-cli
        cd openwrt_sdk/package/luci-app-xray
        conventional-changelog -p angular -r 2 -i CHANGELOG.md -s

    - name: Upload ChangeLog
      uses: actions/upload-artifact@v4
      with:
        name: luci-app-xray-changelog
        path: openwrt_sdk/package/luci-app-xray/CHANGELOG.md

    - name: Build IPK package
      run: |
        cd openwrt_sdk
        make defconfig
        make package/luci-app-xray/status/{clean,compile} V=s -j$(nproc)

    - name: Upload .ipk package
      uses: actions/upload-artifact@v4
      with:
        name: luci-app-xray-ipk
        path: openwrt_sdk/bin/packages/x86_64/base/luci-app-xray*.ipk

  release:
    runs-on: ubuntu-latest
    needs: [build_ipk, build_apk]
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
    - name: Display structure of downloaded files
      run: ls -R
    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        files: |
          luci-app-xray-apk/*.apk
          luci-app-xray-ipk/*.ipk
        body_path: luci-app-xray-changelog/CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
